##########
# Prompt #
##########
# format = """
# $line_break
#    [┌─{{ ](bold 105)$username$hostname$directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# $cmake\
# $rust\
# $golang\
# $conda\
# $python\
# $nodejs\
# $swift\
# $lua\
# [}} ](bold 105)
#    [└─](bold 105)$jobs[ λ ](bold red)
# """
format = """
[  ](bold 105)$username$hostname$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmake\
$rust\
$golang\
$python\
$conda\
$nodejs\
$swift\
$lua
[   ](bold 105)$jobs[ λ ](bold red)
"""

right_format = """
$cmd_duration \
$status \
$kubernetes\
$helm\
$terraform\
$aws
"""

add_newline = true
continuation_prompt = "   ▶▶ "


###########
# Configs #
###########
# System
[username]
style_user = "bold blue"
style_root = "bold red"
format = " [$user]($style) in "
show_always = false
disabled = false

[hostname]
ssh_only = true
style = "red"
format = "[@ $hostname]($style) "
disabled = false

[directory]
read_only = '  '
read_only_style = 'dimmed red'
style = 'bold 105'
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "../"
disabled = false

[cmd_duration]
min_time = 100
show_milliseconds = false
format = "took [$duration]($style)"
style = "bold grey"
disabled = false

[status]
disabled = false

[jobs]
threshold = 1
symbol_threshold = 1
symbol = ""
style = 'red'
format = "[└─{](bold 105)[$symbol$number]($style)[}─](bold 105)"
disabled = false

# Git
[git_branch]
disabled = false

[git_commit]
tag_symbol = ""
format = "[\\(*$hash $tag\\)]($style) "
only_detached = true
tag_disabled = false
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false


# Devops
[kubernetes]
style = 'bold dimmed white'
symbol = "ﴱ"
format = '[=> [$symbol]_kube $context( \($namespace\))]($style) '
disabled = false

[helm]
style = 'bold dimmed white'
symbol = "⎈"
format = '[\[ [$symbol]($style)_helm $version \]]($style) '
disabled = false

[terraform]
style = 'bold dimmed white'
symbol = ""
format = '[\[ [$symbol]($style)_terraform $workspace \]]($style) '
disabled = false

[aws]
style = 'bold dimmed white'
symbol = ""
format = '[=> $symbol]($style)_AWS ($profile )(\($region\))(\[$duration\])]($style) '
disabled = false


# Programming
[cmake]
disabled = false

[conda]
disabled = false

[python]        
disabled = false

[nodejs]
disabled = false

[lua]
disabled = false

[swift]
disabled = false

[rust]
disabled = false

[golang]
disabled = false



############
# Disabled #
############
[nix_shell]
symbol = ""
disabled = true

[julia]
disabled = true

# Maybe in the future
[git_metrics]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

[package]
disabled = true

[java]
disabled = true

[kotlin]
disabled = true

[rlang]
disabled = true

[deno]
disabled = true

[perl]
disabled = true

[ruby]
disabled = true

[scala]
disabled = true


[battery]
disabled = true

[memory_usage]
disabled = true

[sudo]
disabled = true

[time]
disabled = true

[shell]
disabled = true

[shlvl]
disabled = true


# Don't need
[docker_context]
disabled = true

[cobol]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[red]
disabled = true

[singularity]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true














