### ZPROFILE ###
# Anything not directly linked with zsh goes here

# Default fzf command
export FZF_DEFAULT_COMMAND="rg --color=auto --files --smart-case --hidden --follow --glob '!.git'"

# Starship prompt
export STARSHIP_CONFIG=$ZDOTDIR/starship.toml


