### zshenv ###
# Zsh configs directory
export ZDOTDIR=$HOME/.config/zsh

# Zsh history
export HISTFILE="${ZDOTDIR}/.zsh_history"
export SAVEHIST=10000
export HISTSIZE=10000
export HISTFILESIZE=10000
export HISTTIMEFORMAT="[%F %T] "

# Default applications
export LANG=en_US.UTF-8
export PAGER=less

export EDITOR="nvim"
export TERMINAL="iterm2"
export BROWSER="firefox"
export READER="zathura"
export PLAYER="spotify"

