#!/bin/sh 

[ -f ~/.bashrc ] && source ~/.bashrc 

# Profile file that runs on login.
export LANG=en_US.UTF-8
export PATH="$PATH:$HOME/scripts"
export EDITOR="vim"
export TERMINAL="urxvt"
export BROWSER="qutebrowser"
export TRUEBROWSER="firefox"
export READER="zathura"
export PLAYER="spotify"

# Start graphical server 
# if [ "$(tty)" = "/dev/tty1" ]; then
#   pgrep -x i3 || start x
# fi


# case insensitive autocompletion
bind "set completion-ignore-case on"

